services:
  coursera-blockchain-truffle:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "${IMAGE_NAME}:${IMAGE_TAG}" # sets image name and version
    container_name: "${CONTAINER_BASE}" # sets container name
    ports:
      - "8545:3000"
