services:
  ibkr-charts:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: ibkr-charts-image:0.2 # sets image name and version
    container_name: "ibkr-charts"
    environment:
      IBKR_ACCOUNT_ID: "U15794033"
    ports:
      - "5055:5054"
